---
- hosts: localhost
  connection: local
  vars:
    hetzner_api_token: "{{ lookup('env','HETZNER_API_TOKEN') }}"
  tasks:
    - name: create VMs 
      include_tasks: create_vm.yml
      loop:
        - k8s-1
        - k8s-2
        - k8s-3
