---
- hosts: localhost
  connection: local
  vars:
    hetzner_api_token: "{{ lookup('env','HETZNER_API_TOKEN') }}"
  tasks:
    - name: create hetzner machine
      hcloud_server:
        name: "{{ item }}"
        server_type: "cx31"
        image: "debian-10"
        datacenter: "nbg1-dc3"
        api_token: "{{ hetzner_api_token }}"
        ssh_keys:
          - "devops"
        state: present
      loop:
        - k8s-1
        - k8s-2
        - k8s-3
