---
- hosts: localhost
  connection: local
  vars:
    hetzner_api_token: "{{ lookup('env','HETZNER_API_TOKEN') }}"
  tasks:
    - name: destroy hetzner machine
      hcloud_server:
        name: "{{ item }}"
        api_token: "{{ hetzner_api_token }}"
        state: absent
      loop:
        - k8s-1
        - k8s-2
        - k8s-3
    - pause: 
        seconds: 10
    - name: destroy hetzner volume
      hcloud_volume:
        api_token: "{{ hetzner_api_token }}"
        name: "{{ item }}"
        state: absent
      loop:
        - k8s-1
        - k8s-2
        - k8s-3

